version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=flask_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ingrad